#!/data/data/com.termux/files/usr/bin/bash

REPO="https://raw.githubusercontent.com/arounxaillhc-cyber/Roblox-Rejoin/main"

echo "Updating Roblox Rejoin..."

curl -fsSL "$REPO/roblox_rejoin.sh" -o "$HOME/roblox_rejoin.sh"

if [ $? -ne 0 ]; then
    echo "Update failed."
    exit 1
fi

chmod +x "$HOME/roblox_rejoin.sh"

echo "Update complete."
